network:
  layers:
    - input: 2500
      output: 100
      activation: tanh
    - input: 100
      output: 50
      activation: tanh
    - input: 50
      output: 4
      activation: softmax
  loss: cross_entropy
  regularization: 
    type: l2
    rate: 0.001
  weight_init_std: 0.1

training:
  batch_size: 7000
  epochs: 10000
  learning_rate: 0.012

data:
  size: 50
  quantity: 50000
  noise: 0
  split:
    train: 0.7
    val: 0.2
    test: 0.1
  flatten: true