network:
  layers:
    - input: 2500
      output: 4
      activation: tanh
    - input: 4
      output: 4
      activation: softmax
  loss: cross_entropy
  regularization: 
    type: l1
    rate: 0.001
  weight_init_std: 0.01

training:
  batch_size: 700
  epochs: 1000
  learning_rate: 0.01

data:
  size: 50
  quantity: 1000
  noise: 100
  split:
    train: 0.7
    val: 0.2
    test: 0.1
  flatten: true