network:
  layers:
    - input: 2500
      output: 1024
      activation: relu
    - input: 1024
      output: 256
      activation: relu
    - input: 256
      output: 64
      activation: tanh
    - input: 64
      output: 4
      activation: softmax
  loss: cross_entropy
  regularization: 
    type: l2
    rate: 0.01
  weight_init_std: 0.01

training:
  batch_size: 256
  epochs: 100
  learning_rate: 0.02

data:
  size: 50
  quantity: 1000
  noise: 0
  split:
    train: 0.7
    val: 0.2
    test: 0.1
  flatten: true